### ISSUE TITLE
About the VAE

### ISSUE THREAD

**Issue by Haochen-Wang409** [LTH14/mar#3]
Hi @LTH14, what a great work!

I found that the provided VAE checkpoint in this repo (https://www.dropbox.com/scl/fi/hhmuvaiacrarfg28qxhwz/kl16.ckpt?rlkey=l44xipsezc8atcffdp4q7mwmh&dl=0) is different than the original checkpoint provided by LDM (https://ommer-lab.com/files/latent-diffusion/kl-f16.zip).

I have tested the reconstruction FID on ImageNet-256x256. The results are as follows:

|          | rFID | rIS    |
|----------|------|--------|
| LDM-KL16 | 0.82 | 204.77 |
| MAR-KL16 | 0.53 | 210.12 |

The KL-16 VAE of MAR performs much better than that of LDM. Did you train the VAE from scratch? If so, could you provide more details about the training of VAE?

**Comment by yuhuUSTC** [comment]
Maybe in table 2. MAR-KL16 is trained on ImageNe; the LDM-KL16 is trained on OpenImages.

**Comment by LTH14** [comment]
> Hi @LTH14, what a great work!
> 
> I found that the provided VAE checkpoint in this repo (https://www.dropbox.com/scl/fi/hhmuvaiacrarfg28qxhwz/kl16.ckpt?rlkey=l44xipsezc8atcffdp4q7mwmh&dl=0) is different than the original checkpoint provided by LDM (https://ommer-lab.com/files/latent-diffusion/kl-f16.zip).
> 
> I have tested the reconstruction FID on ImageNet-256x256. The results are as follows:
> 
> rFID	rIS
> LDM-KL16	0.82	204.77
> MAR-KL16	0.53	210.12
> The KL-16 VAE of MAR performs much better than that of LDM. Did you train the VAE from scratch? If so, could you provide more details about the training of VAE?

Thanks for your interest! @yuhuUSTC is correct: the original KL VAE in LDM is trained on OpenImages which is much larger than ImageNet (and also there's a domain gap). To make a fair comparison with previous works which are only trained on ImageNet, we train a tokenizer almost following [LDM's recipe](https://github.com/CompVis/latent-diffusion/blob/main/models/first_stage_models/kl-f16/config.yaml), except that we use a batch size of 256 and lr of 1e-4 (for faster training on more GPUs) and decoder is without attention (we forgot to include it when we adapt the code).

In Table 2 of the paper, we ablate our new tokenizer and the official LDM tokenizer (second and last row). Our tokenizer achieves slightly better performance (likely because it is trained on ImageNet), so we use it for the state-of-the-art comparison in Table 4. However, it is totally fine to use the original LDM tokenizer as it also achieves quite a good performance (especially on custom datasets as LDM's tokenizer is trained on much larger OpenImages). The only thing you will need to change is the hard-coded 0.2325 scaling factor to the LDM scaling factor (e.g. 0.18215 for the one used in stable diffusion).

**Comment by Haochen-Wang409** [comment]
Thanks for the prompt reply! That's quite clear to me.

**Comment by xiazhi1** [comment]
> > Hi @LTH14, what a great work!
> > I found that the provided VAE checkpoint in this repo (https://www.dropbox.com/scl/fi/hhmuvaiacrarfg28qxhwz/kl16.ckpt?rlkey=l44xipsezc8atcffdp4q7mwmh&dl=0) is different than the original checkpoint provided by LDM (https://ommer-lab.com/files/latent-diffusion/kl-f16.zip).
> > I have tested the reconstruction FID on ImageNet-256x256. The results are as follows:
> > rFID	rIS
> > LDM-KL16	0.82	204.77
> > MAR-KL16	0.53	210.12
> > The KL-16 VAE of MAR performs much better than that of LDM. Did you train the VAE from scratch? If so, could you provide more details about the training of VAE?
> 
> Thanks for your interest! @yuhuUSTC is correct: the original KL VAE in LDM is trained on OpenImages which is much larger than ImageNet (and also there's a domain gap). To make a fair comparison with previous works which are only trained on ImageNet, we train a tokenizer almost following [LDM's recipe](https://github.com/CompVis/latent-diffusion/blob/main/models/first_stage_models/kl-f16/config.yaml), except that we use a batch size of 256 and lr of 1e-4 (for faster training on more GPUs) and decoder is without attention (we forgot to include it when we adapt the code). Since the changes are really minor and are not our paper's contribution, we omit the tokenizer training code in this repo and you can directly use LDM's code if you want to train a tokenizer by yourself.
> 
> In Table 2 of the paper, we ablate our new tokenizer and the official LDM tokenizer (second and last row). Our tokenizer achieves slightly better performance (likely because it is trained on ImageNet), so we use it for the state-of-the-art comparison in Table 4. However, it is totally fine to use the original LDM tokenizer as it also achieves quite a good performance. I would also recommend using LDM's tokenizer on custom image datasets as it is trained on much larger OpenImages. The only thing you will need to change is the VAE and the hard-coded 0.2325 scaling factor to the LDM scaling factor (e.g. 0.18215 for the one used in stable diffusion).

Hi , I am now trying to use LDM's tokenizer to train my own dataset. Do I need to unfreeze the LDM vae training to make it better suit my dataset?

**Comment by LTH14** [comment]
@xiazhi1 LDM's tokenizer is trained on OpenImage and should be able to tokenize and reconstruct most images. You could visualize the reconstruction results on your dataset to see whether the tokenizer suits your dataset. If not, you could consider fine-tune the tokenizer on your dataset. However, during MAR training, the LDM should always be frozen.

**Comment by xiazhi1** [comment]
> @xiazhi1 LDM's tokenizer is trained on OpenImage and should be able to tokenize and reconstruct most images. You could visualize the reconstruction results on your dataset to see whether the tokenizer suits your dataset. If not, you could consider fine-tune the tokenizer on your dataset. However, during MAR training, the LDM should always be frozen.

Thank you for your assistance !
